algoritmo "media"
// F9: Executa o código

// Autor: Thiago
// Disciplina: LOPAL
// Data: 07/04/2026
var
n1, n2, n3, media: real
inicio
      // Entrada
      escreva ("Informe a primeira nota: ")
      leia (n1)
      
      escreva ("Informe a segunda nota: ")
      leia (n2)
      
      escreva ("Informe a terceira nota: ")
      leia (n3)
      
      // Processo
      media <- (n1 + n2 + n3) / 3
      
      // Saída
      escreva ("Média: ", media)
fimalgoritmo
