algoritmo "area"
// F9: Executa o código

// Autor: Thiago
// Disciplina: LOPAL
// Data: 07/04/2026
var
comprimento, largura, area: real
inicio
      // Entrada
      escreva ("Informe o comprimento: ")
      leia (comprimento)
      
      escreva ("Informe a largura: ")
      leia (largura)
      
      // Processo
      area <- largura * comprimento
      
      // Saída
      escreva ("Área: ", area)
fimalgoritmo
